all:
#	gcc Demo_08_LinkedList_tranditionalWay.c -o Demo_08_LinkedList_tranditionalWay
	gcc Demo_08_LinkedList_doublePointer.c -o Demo_08_LinkedList_doublePointer

clean:
#	rm Demo_08_LinkedList_tranditionalWay
	rm Demo_08_LinkedList_doublePointer


.PHONY: clean
